# Generated by Django 6.1.dev20260226132733 on 2026-04-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('OTHER', 'Other')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('vaccination_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=10)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelter')),
            ],
        ),
    ]
