# Generated by Django 6.1.dev20260226132733 on 2026-04-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='has_other_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='hours_alone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='housing_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='near_park',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
